/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class node_NodeDynamicProxyClass */

#ifndef _Included_node_NodeDynamicProxyClass
#define _Included_node_NodeDynamicProxyClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     node_NodeDynamicProxyClass
 * Method:    callJs
 * Signature: (JLjava/lang/reflect/Method;[Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_node_NodeDynamicProxyClass_callJs
  (JNIEnv *, jobject, jlong, jobject, jobjectArray);

/*
 * Class:     node_NodeDynamicProxyClass
 * Method:    unref
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_node_NodeDynamicProxyClass_unref
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
